Issue 4 fix

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -164,11 +164,15 @@ function start() {
 function stop() {
   echo "Stopping $cartridge_type cart"
 
-  if isrunning; then
+  if ishttpup; then
+   	${WASND_PROFILE_DIR}/bin/stopServer.sh ${WASND_SERVER_NAME} 
+  else if isrunning; then
     if [ -f "$WASND_PID_FILE" ]; then
-      ${WASND_PROFILE_DIR}/bin/stopServer.sh ${WASND_SERVER_NAME} 
-    else
-      echo "Failed to locate WAS ND PID File" 1>&2
+      	pid=$(cat $WASND_PID_FILE);
+        echo "Sending SIGTERM to wasnd:$pid ..." 1>&2
+        killtree $pid
+    else 
+        echo "Failed to locate WAS ND PID File" 1>&2
     fi
   else
      echo "Cart is not running" 
@@ -228,6 +232,39 @@ function threaddump() {
   else 
         echo "Failed to locate WAS ND PID File"
   fi 
+}
+
+# Kill the process given by $1 and its children
+killtree() {
+    local _pid=$1
+    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
+        killtree ${_child}
+    done
+
+    local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+    if [ -z "$should_be_gone_pid" ]; then
+        return
+    else
+        kill -TERM ${_pid}
+    fi
+
+    local count=0
+    while [ ${count} -lt 15 ]
+    do
+        local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+        if [ -z "$should_be_gone_pid" ]; then
+                return
+        else
+                sleep 2
+                let count=${count}+1
+        fi
+    done
+
+    local should_be_gone_pid=$(ps -o pid -p ${_pid} --no-headers)
+    if [ ! -z $should_be_gone_pid ]
+    then
+        kill -9 ${_pid}
+    fi
 }
 
 case "$1" in
