Changed control stop

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -164,19 +164,19 @@ function start() {
 function stop() {
   echo "Stopping $cartridge_type cart"
 
-  if ismgmtup; then
+  if isrunning; then
+  	 if ismgmtup; then
     	echo Calling ${WASND_PROFILE_DIR}/bin/stopServer.sh ${WASND_SERVER_NAME}
    		${WASND_PROFILE_DIR}/bin/stopServer.sh ${WASND_SERVER_NAME}
-  elif isrunning; then
-    	if [ -f "$WASND_PID_FILE" ]; then
-      		pid = $(cat $WASND_PID_FILE);
-        	echo "Sending SIGTERM to wasnd:$pid ..." 1>&2
-        	killtree $pid
-    	else 
-        	echo "Failed to locate WAS ND PID File" 1>&2
-    	fi
+  	 elif [ -f "$WASND_PID_FILE" ]; then
+    	pid = $(cat $WASND_PID_FILE);
+        echo "Sending SIGTERM to wasnd:$pid ..." 1>&2
+        killtree $pid
+     else 
+        echo "Failed to locate WAS ND PID File" 1>&2
+     fi
   else
-     	echo "Cart is not running" 
+     echo "Cart is not running" 
   fi
   
   echo "Cart $cartridge_type stopped"
